[book]
authors = ["rwietter"]
language = "en"
multilingual = false
src = "src"
title = "vault7"
url = "https://rwietter.github.io/vault7"


[output.html]
mathjax-support = true
toc = true

[output.html.fold]
enable = true
